version: '3.9'

services:
  flask:
    container_name: Flask
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile.dev
    platform: linux/x86_64
    ports:
      - "5000:5000"
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: MySQL
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile.dev
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env.development
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.development
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PMA_ACCESS_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

