services:
  flask:
    container_name: Flask
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile.dev
    platform: linux/x86_64
    ports:
      - "50000:5000"
    volumes:
      - ./ChatApp:/app
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    env_file:
      - .env.development
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: MySQL
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile.dev
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./Docker/MySQL/init_dev.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.development
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.development
    ports:
      - "4000:80"
    volumes:
      - phpmyadmin:/sessions
    depends_on:
      - db

volumes:
  mysql_data:
  phpmyadmin: